### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by edgar-mtz-e** [fuzeman/Rosalind.NET#1]
I want to use [Sourcegraph](https://sourcegraph.com) for Rosalind.NET code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/fuzeman/Rosalind.NET. (It should only take 30 seconds.)

Thank you!

**Comment by edgar-mtz-e** [comment]
I keep on getting 
" Repository is not supported. Sourcegraph's advanced code search, browsing, and usage examples are only available for supported languages. If the language was detected incorrectly, or to use only basic repository operations, you can proceed anyway.

This repository must be enabled to use on Sourcegraph"....

**Comment by fuzeman** [comment]
> Repository is not supported.
> 
> Sourcegraph's advanced code search, browsing, and usage examples are only available for Go and Java. If the language was detected incorrectly, or to use only basic repository operations, you can proceed anyway.

Don't think an empty repository is that useful on sourcegraph anyway :smile:
